import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { GlobalTemplate } from "@/components/templates";

const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <GlobalTemplate>{children}</GlobalTemplate>
      </body>
    </html>
  );
}
