openapi: 3.0.1
info:
  title: Tasks API
  description: API for managing tasks
  version: 1.0.0
servers:
  - url: http://localhost:3333
paths:
  /api/tasks:
    get:
      summary: Get all tasks
      tags:
        - Tasks
      responses:
        200:
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
        500:
          description: Internal server error
    post:
      summary: Create a new task
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewTask"
      responses:
        201:
          description: Task created successfully
        500:
          description: Internal server error

  /api/tasks/{id}:
    get:
      summary: Get a task by ID
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Task details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        404:
          description: Task not found
    put:
      summary: Update a task
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTask"
      responses:
        200:
          description: Task updated successfully
        404:
          description: Task not found
    delete:
      summary: Delete a task
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Task deleted successfully
        404:
          description: Task not found

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [PENDING, IN_PROGRESS, COMPLETED]
        dueDate:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    NewTask:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [PENDING, IN_PROGRESS, COMPLETED]
        dueDate:
          type: string
          format: date-time

    UpdateTask:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [PENDING, IN_PROGRESS, COMPLETED]
        dueDate:
          type: string
          format: date-time