services:
  api:
    container_name: backend-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://developer:localdev@postgres:5432/taskdb
      - PORT=3333
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  postgres:
    container_name: backend-postgres
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: localdev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d taskdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 